name: tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  id-token: write   # <-- required for OIDC auth to Codecov

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package + test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest -q --cov=scifi_demux --cov-report=xml

      # EITHER OIDC (recommended, no token)
      - name: Upload coverage to Codecov (OIDC)
        uses: codecov/codecov-action@v4
        with:
          use_oidc: true
          fail_ci_if_error: true
          verbose: true

      # OR (comment OIDC step above and uncomment this block)
      # - name: Upload coverage to Codecov (token)
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error: true
      #     verbose: true
